### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by yufengwhy** [samsledje/MLSB2021_PLM_DTI#4]
where is a trained model to predict?

**Comment by samsledje** [comment]
Please see https://github.com/samsledje/ConPLex, where a pre-trained model can be downloaded using `conplex-dti download`. We are currently working on implementing a `predict` script, please check back shortly!

**Comment by yufengwhy** [comment]
@samsledje 
1. Do we need only **one** model (conplex-dti downloaded) to reproduce all results in the paper ?
2. where to find train_plm_dti.py and train_plm_dti-TDC-DG.py used in the scripts folder?
3. where is the script for "predictions for the human proteome against all drugs in ChEMBL in just under 24 h"

**Comment by samsledje** [comment]
1. The results on each benchmark data set are from a different model trained on that specific data set -- actually several, since we run several random initializations and average their results. The one model currently available with the package is the one used to make the predictions for experimental validation, and the one we recommend to make predictions if you'd like to just get started without training your own model.
2. These are old, and the scripts need to be updated, thanks for bringing this to my attention! The main entry point for any model training is just `train_DTI.py`
3. The all-vs-all was performed using `genome_wide_scan.py.`

**Comment by yufengwhy** [comment]
@samsledje 
1. where to find different configs for different model trained by train_DTI.py ?
3.  where to find data and ckp in genome_wide_scan.py ?

**Comment by samsledje** [comment]
1. You can update the `default_config.yaml` with different values of `task` to train for different benchmark data sets
2. We used data from STRING for protein sequences and from ChEMBL for small molecules -- that data is publicly available. The checkpoint we used can be downloaded using `conplex-dti download` from the official package.

**Comment by yufengwhy** [comment]
@samsledje 
2. would you kindly provide the detail links of the data? thanks~
